# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  #
  # Please add items below based on alphabetical order
  projects:
    - name: cmsis
      revision: c3bd2094f92d574377f7af2aec147ae181aa5f8e
      path: modules/hal/cmsis
    - name: hal_atmel
      revision: d17b7dd92d209b20bc1e15431d068edc29bf438d
      path: modules/hal/atmel
    - name: hal_altera
      revision: 23c1c1dd7a0c1cc9a399509d1819375847c95b97
      path: modules/hal/altera
    - name: canopennode
      path: modules/lib/canopennode
      revision: 468d350028a975b96563e58344de48281a0ab371
    - name: civetweb
      revision: e6903b80c09d17cd1a8bb32e40080005558aad29
      path: modules/lib/civetweb
    - name: hal_espressif
      west-commands: west/west-commands.yml
      revision: 17269ae883441d3dd8498b7f170cf9cb421edc05
      path: modules/hal/espressif
    - name: fatfs
      revision: 1d1fcc725aa1cb3c32f366e0c53d7490d0fe1109
      path: modules/fs/fatfs
    - name: hal_cypress
      revision: a12d92816a53a521d79cefcf5c38b9dc8a4fed6e
      path: modules/hal/cypress
    - name: hal_infineon
      revision: f1fa8241f8786198ba41155413243de36ed878a5
      path: modules/hal/infineon
    - name: hal_nordic
      revision: 46b65a5a6ebb6d089431bc80a4f78746c1c90a88
      path: modules/hal/nordic
    - name: hal_openisa
      revision: 40d049f69c50b58ea20473bee14cf93f518bf262
      path: modules/hal/openisa
    - name: hal_nuvoton
      revision: b4d31f33238713a568e23618845702fadd67386f
      path: modules/hal/nuvoton
    - name: hal_microchip
      revision: a1ec761014740a08699720298dd37ad4da360840
      path: modules/hal/microchip
    - name: hal_silabs
      revision: de93f34488f2ab4d6337af0819b377636034fcda
      path: modules/hal/silabs
    - name: hal_st
      revision: b52fdbf4b62439be9fab9bb4bae9690a42d2fb14
      path: modules/hal/st
    - name: hal_stm32
      revision: 50283e0438d882a80fb681907664491c7042c817
      path: modules/hal/stm32
    - name: hal_ti
      revision: 277d70a65ab14d46bf1ec0935cf9bb28bbaa8ab9
      path: modules/hal/ti
    - name: libmetal
      revision: 9d4ee2c3cfd5f49861939447990f3b7d7bf9bf94
      path: modules/hal/libmetal
    - name: hal_quicklogic
      repo-path: hal_quicklogic
      revision: b3a66fe6d04d87fd1533a5c8de51d0599fcd08d0
      path: modules/hal/quicklogic
    - name: lvgl
      revision: 31acbaa36e9e74ab88ac81e3d21e7f1d00a71136
      path: modules/lib/gui/lvgl
    - name: mbedtls
      revision: 24d84ecff195fb15c889d9046e44e4804d626c67
      path: modules/crypto/mbedtls
    - name: mcuboot
      revision: 846b104e67c46f9428fd020ba8dccf94f786d94d
      path: bootloader/mcuboot
    - name: mcumgr
      revision: 9f09bae7c0ad7df5e0a72731061125913fba61c7
      path: modules/lib/mcumgr
    - name: net-tools
      revision: 41132e9220f8bc1223084975350c5e5f3b492afe
      path: tools/net-tools
    - name: hal_nxp
      revision: b916bca1d5976b0157be80b326e3bb46ef605286
      path: modules/hal/nxp
    - name: open-amp
      revision: de1b85a13032a2de1d8b6695ae5f800b613e739d
      path: modules/lib/open-amp
    - name: loramac-node
      revision: 2cee5f7295ff0ff804bf06fea5de006bc7cd121e
      path: modules/lib/loramac-node
    - name: openthread
      revision: fd27fc3a7758d409e00d0e8d43f3f8364ce6c7e9
      path: modules/lib/openthread
    - name: segger
      revision: 38c79a447e4a47d413b4e8d34448316a5cece77c
      path: modules/debug/segger
    - name: sof
      revision: b5b772dd611879ee6309da38759def79fc7f33f1
      path: modules/audio/sof
    - name: tinycbor
      path: modules/lib/tinycbor
      revision: 40daca97b478989884bffb5226e9ab73ca54b8c4
    - name: tinycrypt
      path: modules/crypto/tinycrypt
      revision: 3e9a49d2672ec01435ffbf0d788db6d95ef28de0
    - name: littlefs
      path: modules/fs/littlefs
      revision: 9e4498d1c73009acd84bb36036ee5e2869112a6c
    - name: mipi-sys-t
      path: modules/debug/mipi-sys-t
      revision: 75e671550ac1acb502f315fe4952514dc73f7bfb
    - name: nrf_hw_models
      path: modules/bsim_hw_models/nrf_hw_models
      revision: a47e326ca772ddd14cc3b9d4ca30a9ab44ecca16
    - name: hal_xtensa
      revision: 2f04b615cd5ad3a1b8abef33f9bdd10cc1990ed6
      path: modules/hal/xtensa
    - name: edtt
      path: tools/edtt
      revision: 7dd56fc100d79cc45c33d43e7401d1803e26f6e7
    - name: trusted-firmware-m
      path: modules/tee/tfm
      revision: 69dc29a48b707dfe732a57e05a3291ca71138eec
    - name: tfm-mcuboot # This is used by the trusted-firmware-m module.
      repo-path: mcuboot
      path: modules/tee/tfm-mcuboot
      revision: 1.7.0-rc1

  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
